"""add_completed_at_to_batchrun

Revision ID: 23d3f1cf037f
Revises: 3f27bce2d1f3
Create Date: 2026-02-09 17:54:28.481758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d3f1cf037f'
down_revision: Union[str, Sequence[str], None] = '3f27bce2d1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_run', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
