"""Add status fields to ExtractionRun

Revision ID: 80a47444f56c
Revises: dfd62a1b5a01
Create Date: 2026-01-11 21:08:49.031905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a47444f56c'
down_revision: Union[str, Sequence[str], None] = 'dfd62a1b5a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraction_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False, server_default='queued'))
        batch_op.add_column(sa.Column('failure_reason', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('prompts_json', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pdf_url', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_extraction_run_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraction_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_run_status'))
        batch_op.drop_column('pdf_url')
        batch_op.drop_column('prompts_json')
        batch_op.drop_column('failure_reason')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
