"""Add ExtractionRun and ExtractionEntity tables

Revision ID: dfd62a1b5a01
Revises: 
Create Date: 2026-01-11 16:28:54.442109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'dfd62a1b5a01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('raw_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_text_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extraction_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_run_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_run_source_text_hash'), ['source_text_hash'], unique=False)

    op.create_table('extraction_entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('peptide_sequence_one_letter', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('peptide_sequence_three_letter', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('n_terminal_mod', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('c_terminal_mod', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_hydrogel', sa.Boolean(), nullable=True),
    sa.Column('chemical_formula', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('smiles', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('inchi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('labels', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('morphology', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('concentration', sa.Float(), nullable=True),
    sa.Column('concentration_units', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('cac', sa.Float(), nullable=True),
    sa.Column('cgc', sa.Float(), nullable=True),
    sa.Column('mgc', sa.Float(), nullable=True),
    sa.Column('validation_methods', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('process_protocol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reported_characteristics', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['extraction_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extraction_entity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_entity_c_terminal_mod'), ['c_terminal_mod'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_entity_chemical_formula'), ['chemical_formula'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_entity_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_entity_is_hydrogel'), ['is_hydrogel'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_entity_n_terminal_mod'), ['n_terminal_mod'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_entity_peptide_sequence_one_letter'), ['peptide_sequence_one_letter'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_entity_ph'), ['ph'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_entity_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraction_entity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_entity_run_id'))
        batch_op.drop_index(batch_op.f('ix_extraction_entity_ph'))
        batch_op.drop_index(batch_op.f('ix_extraction_entity_peptide_sequence_one_letter'))
        batch_op.drop_index(batch_op.f('ix_extraction_entity_n_terminal_mod'))
        batch_op.drop_index(batch_op.f('ix_extraction_entity_is_hydrogel'))
        batch_op.drop_index(batch_op.f('ix_extraction_entity_entity_type'))
        batch_op.drop_index(batch_op.f('ix_extraction_entity_chemical_formula'))
        batch_op.drop_index(batch_op.f('ix_extraction_entity_c_terminal_mod'))

    op.drop_table('extraction_entity')
    with op.batch_alter_table('extraction_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_run_source_text_hash'))
        batch_op.drop_index(batch_op.f('ix_extraction_run_paper_id'))

    op.drop_table('extraction_run')
    # ### end Alembic commands ###
